### ISSUE TITLE
Error with filter_fails()

### ISSUE THREAD

**Issue by oguchihy** [DavZim/davzim.github.io#1]
Getting this problem with the expression:

rule(!(str_detect(str_to_lower(Pat.Name), str_to_lower("test")) | str_detect(str_to_lower(Pat.Name), paste0("^", str_to_lower("zz"))))),
rule(...)

> filter_fails(res, rules.dt)
Error in parse(text = expr, keep.source = TRUE) : 
  <text>:2:0: unexpected end of input
1: !(str_detect(str_to_lower(Pat.Name), str_to_lower("test")) | 
   ^

I have verified that the expression is correct.

**Comment by DavZim** [comment]
I guess you mean the dataverifyr package and not the website. I'm gonna close this issue, but can you please open one [here](https://github.com/DavZim/dataverifyr/issues). 

Also, can you post a full reproducible example, including a small dataset and the backend you are using (eg data.table, dplyr, ...) that allows me to troubleshoot.

Thank you.
